const skillsOptions = [
  {value: "data_structures", label: "Data Structures"},
  {value: "sql", label: "SQL"},
  {value: "leadership", label: "Leadership"},
  {value: "web_development", label: "Web Development"},
  {value: "java", label: "Java"},
  {value: "creative_thinking", label: "Creative Thinking"},
  {value: "coding", label: "Coding"},
  {value: "javascript", label: "JavaScript"},
  {value: "critical_thinking", label: "Critical Thinking"},
  {value: "open_source", label: "Open Source Experience"},
  {value: "csharp", label: "C#"},
  {value: "communication", label: "Communication"},
  {value: "machine_learning", label: "Machine Learning"},
  {value: "python", label: "Python"},
  {value: "collaboration", label: "Collaboration"},
  {value: "security", label: "Security"},
  {value: "cplusplus", label: "C++"},
  {value: "calm_demeanor", label: "Calm Demeanor"},
  {value: "math", label: "Math"},
  {value: "php", label: "PHP"},
  {value: "enthusiasm", label: "Enthusiasm"},
  {value: "logic", label: "Logic"},
  {value: "ios", label: "IOS"},
  {value: "inquisitiveness", label: "Inquisitiveness"},
  {value: "networks", label: "Networks"},
]
export default skillsOptions