export const skillsOptions = [
  {value: "data_structures", label: "Data Structures"},
  {value: "sql", label: "SQL"},
  {value: "leadership", label: "Leadership"},
  {value: "web_development", label: "Web Development"},
  {value: "java", label: "Java"},
  {value: "creative_thinking", label: "Creative Thinking"},
  {value: "coding", label: "Coding"},
  {value: "javascript", label: "JavaScript"},
  {value: "critical_thinking", label: "Critical Thinking"},
  {value: "open_source", label: "Open Source Experience"},
  {value: "csharp", label: "C#"},
  {value: "communication", label: "Communication"},
  {value: "machine_learning", label: "Machine Learning"},
  {value: "python", label: "Python"},
  {value: "collaboration", label: "Collaboration"},
  {value: "security", label: "Security"},
  {value: "cplusplus", label: "C++"},
  {value: "calm_demeanor", label: "Calm Demeanor"},
  {value: "math", label: "Math"},
  {value: "php", label: "PHP"},
  {value: "enthusiasm", label: "Enthusiasm"},
  {value: "logic", label: "Logic"},
  {value: "ios", label: "IOS"},
  {value: "inquisitiveness", label: "Inquisitiveness"},
  {value: "networks", label: "Networks"},
]

export const messages = [
  "It's just not a good fit at this time.",
  "Let's not kid ourselves.",
  "It is always good to dream, but maybe you should be realistic today.",
  "With those credentials? I don't think so.",
  "Make like a bee and bug off.",
  "Perhaps you should reconsider the life choices that have put you here.",
  "Time is money. You owe us for wasting ours.",
  "We are looking for a 10X engineer, not a 0X one.",
  "At least your mother probably thinks you are special.",
  "If we had a choice between you and a monkey, we would hire the monkey.",
  "Perhaps you ended up at the wrong site. Try this site instead: http://disneyjunior.disney.com.au/games",
  "After reviewing your Facebook, we have determined you are too boring to work here.",
  "Your resume has been duly placed in the cylindrical filing cabinet.",
  "Don't worry about waiting for a call.",
  "There's always next time.",
  "Some people are born with brains. Some are born with brawn. Congratulations on taking the road less traveled.",
]